id: I93A61CC8
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-22T02:01:34+00:00'
last_modified: '2022-06-10T10:52:42.620553+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG23521
  title: དུས་གསུམ་རེའུ་མིག་སོམ་ཉིའི་དྲ་བ་གཅོད་པའི་རལ་གྲི།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '3461':
      image_group_id: I1KG23575
      title: ''
      total_pages: 142
      order: 1
      base_file: 3461.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
