id: P002944
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 2021-12-17 10:30:01.726936
source_metadata:
  id: bdr:W1KG23521
  title: དུས་གསུམ་རེའུ་མིག་སོམ་ཉིའི་དྲ་བ་གཅོད་པའི་རལ་གྲི།
  author: ''
  volumes:
    b7b965f010bb4dfeb43b074eb27a9502:
      image_group_id: I1KG23575
      title: ''
      volume_number: 1
      total_pages: 142
      base_file: v001.txt
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
