id: P002944
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG23521
  title: དུས་གསུམ་རེའུ་མིག་སོམ་ཉིའི་དྲ་བ་གཅོད་པའི་རལ་གྲི།
  author: ''
  volumes:
    b7b965f010bb4dfeb43b074eb27a9502:
      image_group_id: I1KG23575
      title: ''
      volume_number: 1
      total_pages: 142
